import { Tool } from "@/types/tool";

export const TOOLS: Tool[] = [
  {
    id: "1",
    slug: "ai-chat",
    title: "AI Chat",
    description: "Instant intelligent assistant for questions and brainstorming.",
    category: "Productivity",
    iconName: "MessageSquare",
    gradient: "from-orange-500 to-red-600",
    badge: "NEW",
    inputLabel: "Ask anything...",
    placeholderText: "What are 5 actionable strategies to improve focus?",
  },
  {
    id: "2",
    slug: "ai-content-writer",
    title: "Content Writer",
    description: "Generate engaging blog posts, articles, and long-form writing.",
    category: "Writing",
    iconName: "Download",
    gradient: "from-purple-600 to-indigo-700",
    inputLabel: "Describe your topic...",
    placeholderText: "Write a short article about future tech trends.",
  },
  {
    id: "3",
    slug: "grammar-checker",
    title: "Grammar Checker",
    description: "Fix grammar, spelling, and phrasing instantly.",
    category: "Writing",
    iconName: "QrCode",
    gradient: "from-lime-500 to-emerald-600",
    inputLabel: "Paste text to check...",
    placeholderText: "Paste your raw text here to correct errors.",
  },
  {
    id: "4",
    slug: "text-rewriter",
    title: "Text Rewriter",
    description: "Rephrase text to improve tone, flow, and vocabulary.",
    category: "Writing",
    iconName: "Broom",
    gradient: "from-neutral-700 to-zinc-900",
    inputLabel: "Paste text to rewrite...",
    placeholderText: "Rewrite this sentence professionally.",
  },
  {
    id: "5",
    slug: "ai-summarizer",
    title: "AI Summarizer",
    description: "Condense articles and documents into concise key points.",
    category: "Productivity",
    iconName: "Camera",
    gradient: "from-cyan-500 to-teal-700",
    inputLabel: "Paste long text...",
    placeholderText: "Paste text here to get a quick summary.",
  },
  {
    id: "6",
    slug: "ai-translator",
    title: "AI Translator",
    description: "Translate text accurately into 50+ languages.",
    category: "Productivity",
    iconName: "MessageCircle",
    gradient: "from-pink-500 to-rose-600",
    badge: "NEW",
    inputLabel: "Enter text & target language...",
    placeholderText: "Translate to Spanish: Welcome to our app!",
  },
  {
    id: "7",
    slug: "ai-email-writer",
    title: "Email Writer",
    description: "Draft professional, clear emails in seconds.",
    category: "Productivity",
    iconName: "Mail",
    gradient: "from-red-500 to-rose-700",
    inputLabel: "Describe the email topic...",
    placeholderText: "Write a polite follow-up email after a meeting.",
  },
  {
    id: "8",
    slug: "explain-anything",
    title: "Explain Anything",
    description: "Understand complex topics in simple terms.",
    category: "Education",
    iconName: "PhoneCall",
    gradient: "from-amber-400 to-yellow-600",
    inputLabel: "Topic or question...",
    placeholderText: "Explain how solar panels produce electricity.",
  },
  {
    id: "9",
    slug: "ai-bio-generator",
    title: "Bio Generator",
    description: "Craft memorable bios for social media & LinkedIn.",
    category: "Social",
    iconName: "User",
    gradient: "from-emerald-500 to-teal-700",
    inputLabel: "Your role & skills...",
    placeholderText: "Software developer passionate about mobile apps.",
  },
  {
    id: "10",
    slug: "ai-caption-generator",
    title: "Caption Generator",
    description: "Generate viral social media captions with hashtags.",
    category: "Social",
    iconName: "Sparkles",
    gradient: "from-fuchsia-600 to-pink-600",
    inputLabel: "Post topic or photo description...",
    placeholderText: "Sunset view at the beach during vacation.",
  },
  {
    id: "11",
    slug: "ai-name-generator",
    title: "Name Generator",
    description: "Brainstorm catchy brand, startup, and app names.",
    category: "Creative",
    iconName: "Lightbulb",
    gradient: "from-blue-600 to-indigo-700",
    inputLabel: "Describe your concept...",
    placeholderText: "An AI tool app for mobile devices.",
  },
  {
    id: "12",
    slug: "ai-homework-helper",
    title: "Homework Helper",
    description: "Step-by-step guidance for math, science, and study topics.",
    category: "Education",
    iconName: "GraduationCap",
    gradient: "from-violet-600 to-purple-800",
    inputLabel: "Homework question...",
    placeholderText: "Solve step-by-step: 2x + 5 = 15",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}
